[logger]
level = "DEBUG"

[storage]
mode = "sql" # valid values are "sql", "in-memory"
user = "user"
password = "password_1337"
host = "127.0.0.1"
port = 5432
name = "calendar"

[server.http]
host = "localhost"
port = 8080

[server.grpc]
port = 50051
